totem {
    version: 2
    secauth: off
    cluster_name: lab_cluster
    transport: udpu
}

nodelist {
    node {
        ring0_addr: 192.168.10.1
        name: server-1
        nodeid: 1
    }
    node {
        ring0_addr: 192.168.10.2
        name: server-2
        nodeid: 2
    }
}

quorum {
    provider: corosync_votequorum
}

logging {
    to_logfile: yes
    logfile: /var/log/corosync/corosync.log
    to_syslog: yes
    debug: off
}