# Example DHCP server configuration file.
# Minimal sample /etc/dhcp/dhcpd.conf
default-lease-time 600;
max-lease-time 7200;

subnet 192.168.1.0 netmask 255.255.255.0 {
 range 192.168.1.150 192.168.1.200;
 option routers 192.168.1.254;
 option domain-name-servers 192.168.1.1, 192.168.1.2;
 option domain-name "erick-fanka.com";
}

host cliente-vm {
 hardware ethernet 08:00:27:1a:47:c1;
 fixed-address 192.168.1.41;
}